### ISSUE TITLE
ROI(Region of Interest) of avc encding is broken on the master on SKL/APL/KBL

### ISSUE THREAD

**Issue by zzoon** [01org/intel-vaapi-driver#108]
Since the commit e9a0038 landed, it seems that ROI is broken.
In addition, a size of produced h264 data with roi is much more (over ten times) than h264 data's size without roi. Is this expected?

I tested with libva-utils/encode/avcenc and KBL.

**Comment by zzoon** [comment]
I'm sorry for confusing.
I tested on SKL not KBL.

**Comment by QuPengfei** [comment]
@zzoon yes. new improved AVC encoder on SKL/KBL broken the ROI feature. we have plan to enable ROI under CQP in the next step.

**Comment by zzoon** [comment]
Thanks for reply, then I should wait for it. Feel free to close this issue.

**Comment by ceyusa** [comment]
> Thanks for reply, then I should wait for it. Feel free to close this issue.

Perhaps it should remain open, as a remainder of a pending task.
