### ISSUE TITLE
Libva intel-driver(i965) master branch can't decode field VC1

### ISSUE THREAD

**Issue by seanvk** [01org/intel-vaapi-driver#12]
migrated from Bugzilla [#98850](https://bugs.freedesktop.org/show_bug.cgi?id=98850)
status ASSIGNED severity *normal* in component *intel* for *---*
Reported in version *unspecified* on platform *All*
Assigned to: ykzhao

On 2016-11-25 06:24:03 +0000, Jun Zhao wrote:

> We used the file fate-suite/vc1/SA10143.vc1 fate-suite/vc1/ilaced_twomv.vc1, and can get the files with the command:
> 
> rsync -aL rsync://fate-suite.ffmpeg.org:/fate-suite/ fate-suite.

On 2016-11-25 08:54:56 +0000, haihao wrote:

> Yes, this is a known issue, and lower the priority.

**Comment by xhaihao** [comment]
few people is using VC1 on Linux and we have supported basic VC1 in the driver.
