### ISSUE TITLE
[BSW] Insert AUD has wrong order in AVC encoder

### ISSUE THREAD

**Issue by mypopydev** [01org/intel-vaapi-driver#155]
More information, you can refer to: 

https://patchwork.ffmpeg.org/patch/3544/

I know the commit fd52137 fix this issue in GEN9 (I've verified in SKL with master branch), but GEN8 don't have this fix.

**Comment by mypopydev** [comment]
BTW:  I think HEVC Encoder insert AUD has the same issue in BSW/SKL

**Comment by QuPengfei** [comment]
@mypopydev that is correct. we will add the fix later.
