### ISSUE TITLE
[RFC] Enhance multi-ref frame support

### ISSUE THREAD

**Issue by mypopydev** [01org/intel-vaapi-driver#156]
Now VAConfigAttribEncMaxRefFrames only support list 0 == 1 && list 1 == 1,  request more ref frame support in i965 driver.  In most cases, the extra reference frames can improve compression efficiency and/or video quality.

**Comment by xhaihao** [comment]
Close this issue and use https://github.com/01org/intel-vaapi-driver/issues/199 and 
https://github.com/01org/intel-vaapi-driver/issues/200 to track the support for  multi-ref frame
