### ISSUE TITLE
Does SKL support 10bit HEVC decode?

### ISSUE THREAD

**Issue by codeathon** [01org/intel-vaapi-driver#157]
Wanted to find out if HEVC 10bit profile is supported for decode on SKL?
The README does not mention it, so wanted to confirm.

**Comment by uartie** [comment]
The [README](https://github.com/01org/intel-vaapi-driver/blob/master/README) says:

HEVC 10bit     D       BXT+

And in [src/i965_device_info.c](https://github.com/01org/intel-vaapi-driver/blob/master/src/i965_device_info.c#L327), the `.has_hevc10_decoding` is not set for SKL.  So there is no support for HEVC 10bit decode on SKL.

**Comment by ngeorgis** [comment]
Weird.. I remember I was able to decode HEVC 10bit in hybrid mode (not fixed function like on my Kabylake) using VAAPI.  CPU load was 30% to 40% for 10-bit QFHD HEVC on a Skylake Core i7 6770.

**Comment by QuPengfei** [comment]
@ngeorgis i think you are using intel media sdk.

**Comment by ngeorgis** [comment]
No media sdk on this system as I have not patched the kernel yet.

**Comment by uartie** [comment]
If you're using intel media sdk, it is not compatible with this driver.  See media sdk [README](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/README.md) about that.
