### ISSUE TITLE
gen9 H.264 encoder uses mb_rate_control incorrectly

### ISSUE THREAD

**Issue by fhvwy** [01org/intel-vaapi-driver#166]
The va.h header says (va.h:1266):
```
            unsigned int mb_rate_control : 4; /* Control VA_RC_MB 0: default, 1: enable, 2: disable, other: reserved*/
```
The H.264 encoder then does (gen9_avc_encoder.c:427/435):
```
        generic_state->mb_brc_enabled = encoder_context->brc.mb_rate_control[0];
```
and then treats mb_brc_enabled as a boolean thereafter.  This is wrong for mb_rate_control == 2, which should disable it.

(For comparison, the H.265 encoder is correct (gen9_hevc_encoder.c:1702):
```
            if (brc_method == HEVC_BRC_VCM ||
                encoder_context->brc.mb_rate_control[0] == 0)
                priv_state->lcu_brc_enabled = (priv_state->tu_mode == HEVC_TU_BEST_QUALITY);
            else if (brc_method == HEVC_BRC_ICQ ||
                     encoder_context->brc.mb_rate_control[0] == 1)
                priv_state->lcu_brc_enabled = 1;
            else
                priv_state->lcu_brc_enabled = 0;
```
That is: given 0, use a default dependent on the configuration; given 1, enable; given 2, disable.  (Ignoring the ICQ case because it isn't actually enabled in any configuration.))

**Comment by QuPengfei** [comment]
@fhvwy agree. it should be fixed.
