### ISSUE TITLE
AVC encoder improvement on BDW/BSW

### ISSUE THREAD

**Issue by QuPengfei** [01org/intel-vaapi-driver#176]
This focus on the AVC video encoder improvement on the BDW and BSW platform

**Comment by LSL1337** [comment]
on version 2.0 this was addressed.
Is there a remote possibility, that haswell will get this kind of support as well?
Is haswell very different to broadwell?

thanks!

**Comment by QuPengfei** [comment]
HSW will not be improved in the plan. yes, GPU is different between  HSW and BDW.
