### ISSUE TITLE
Memory leak in jpeg_decode

### ISSUE THREAD

**Issue by VitalyGu** [01org/intel-vaapi-driver#190]
### When decoding many jpegs, process memory grow . 

example:
`./test_i965_drv_video --gtest_filter=JPEG/FourCCTest.Decode/0 --gtest_repeat=-1`
For 3 minutes it's grow from 8.6MB to 25.3MB.

My investigation show than its near 
    ASSERT_NO_FAILURE(renderPicture(context, &huffTableBufId));

Hardware:
ibva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /home/vitaly/mesa-debug/intel-vaapi-driver/src/.libs/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0

![_2017-06-02_11-16-45](https://cloud.githubusercontent.com/assets/29140786/26717873/a4ed37ce-4787-11e7-806a-a57903a2fba8.png)
![_2017-06-02_11-17-52](https://cloud.githubusercontent.com/assets/29140786/26717877/a9b27986-4787-11e7-9a8d-fedacbda29bc.png)
![_2017-06-02_11-19-14](https://cloud.githubusercontent.com/assets/29140786/26717881/aed09aec-4787-11e7-855a-d5ce4688b5dd.png)

**Comment by uartie** [comment]
Good catch!
