### ISSUE TITLE
howto get g45-h264 source branch from new release

### ISSUE THREAD

**Issue by andysendo** [01org/intel-vaapi-driver#204]
g45-h264 source banch is very useful, cant find from this repo, SourceForge.net cant download anymore.

**Comment by xhaihao** [comment]
@andysendo, we don't maintain g45-h264 branch any more. you can find g45-h264 branch on people.freedesktop.org/~haihao/libva if you want to use g45-h264.

**Comment by andysendo** [comment]
Browse people.freedesktop.org/~haihao/libva get 403 Forbidden error.
Howto get the source?

**Comment by xhaihao** [comment]
Please navigate your browser to https://cgit.freedesktop.org/~haihao/libva/, you will find the branch names in the top of the page and git repo URL in the bottom of the page. You should contact your IT administrator if you are behind a firewall.

**Comment by xhaihao** [comment]
@andysendo did you get the source code?

**Comment by andysendo** [comment]
yes, i get it. 
i think its too old so there are some compile error.
i get source from https://aur.archlinux.org/packages/libva-intel-driver-g45-h264/ thats newer and runs ok.

Thanks for help.

**Comment by mirh** [comment]
I was wondering.. Why g45-h264 has never been 'mainlined' in 6 years?

**Comment by xhaihao** [comment]
It doesn't play some 1080p videos smoothly.

**Comment by mirh** [comment]
I have read that can happily be addressed by increasing igp dedicated memory
...
But even if that wasn't the case, why couldn't one just limit acceleration to 720p or lower?
