### ISSUE TITLE
How to disable informative messages in .xsession-errors

### ISSUE THREAD

**Issue by effemmeffe** [01org/intel-vaapi-driver#24]
My kodi runs over a NUC with ubuntu 16.04.
The file .xsession-errors is full of messages from vaapi:
```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

```
I reported on kodi forum: http://forum.kodi.tv/showthread.php?tid=305503&pid=2513806#pid2513806 and they told me that this is something outside their control.
Is it possible to disable the print of those messages that fills the file without any valuable information?

**Comment by uartie** [comment]
Unfortunately there is no way to disable it.  Your welcome to propose a patch or file a feature request issue.
