### ISSUE TITLE
[feature request] disable informative messages 

### ISSUE THREAD

**Issue by effemmeffe** [01org/intel-vaapi-driver#26]
In my .xsession-errors I found this messages:
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

I'd like to have the ability to disable those messages.
This will avoid to make the file grow in machines that runs kodi and are not rebooted often.

**Comment by seanvk** [comment]
This information is provided by libva and is not handled by the driver.
