### ISSUE TITLE
[SKL] H264 encoder multi-reference output video mosaic when refs > 5

### ISSUE THREAD

**Issue by mypopydev** [01org/intel-vaapi-driver#272]
Used gstreamer-vaapi do transcode h264 to h264 , when set refs value > 5 , the output video has mosaic 

command : gst-launch-1.0 filesrc blocksize=10000000 location=/home/media/zhouyun/skyfall2-trailer.mp4 ! queue ! qtdemux ! vaapih264dec ! queue ! vaapih264enc refs=6 ! mpegtsmux ! filesink location=test.ts

gstreamer-vaapi version : 2eb2b26ad8d8c3fe9233c9242ae37ebdcec89a3c(libs: decoder: at update_caps() decode codec_data)
kernel version : 4.10.0-33-generic
libva version : 1.8.4.pre1
inter-vaapi-driver version : d22e4ef46924715c475c414c6c5c1f060ff286d8

**Comment by xhaihao** [comment]
According to your descriptor, this is a H264 issue, not HEVC issue, could you update the title?
