### ISSUE TITLE
What is the different between this repo, and github.com/01org/iotg-lin-gfx-libva?

### ISSUE THREAD

**Issue by pauldotknopf** [01org/intel-vaapi-driver#279]
Sorry if it seems like a dumb question, but I am having trouble making sense of all these repositories and figuring out which one I should use.

**Comment by xhaihao** [comment]
https://github.com/01org/libva is the official git repo for libva.

**Comment by pauldotknopf** [comment]
What is the difference between that repo and this intel-vaapi-driver?

Also, what is this one for? https://github.com/01org/iotg-lin-gfx-libva

**Comment by xhaihao** [comment]
> What is the difference between that repo and this intel-vaapi-driver?

iotg-lin-gfx-libva is a fork of libva, not intel-vaapi-driver.  libva is an implementation for VA-API and intel-vaapi-driver is an Intel GEN GPU specific acceleration backend driver for libva. 

> Also, what is this one for? https://github.com/01org/iotg-lin-gfx-libva

You should ask the owner of https://github.com/01org/iotg-lin-gfx-libva
