### ISSUE TITLE
after git pull to try the upgrade from 0.40.1 to new 2.0 i get this:

### ISSUE THREAD

**Issue by estimadarocha** [01org/intel-vaapi-driver#294]
root@BitFenix:~# vainfo
error: can't connect to X server!
libva info: VA-API version 0.40.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/local/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

**Comment by uartie** [comment]
did you recompile vainfo from https://github.com/01org/libva-utils?

**Comment by estimadarocha** [comment]
@uartie no! is it needed?

**Comment by uartie** [comment]
yes
