### ISSUE TITLE
GStreamer VA API multi-stream decode with H264 not more supported for APL

### ISSUE THREAD

**Issue by araani** [01org/intel-vaapi-driver#300]
According to a recent Intel release note multi-stream H264 decoding is not more supported on Intel Apollo Lake (APL) E39XX, N3350 and N4200

The document in question:

Intel Atom® SoC E3900 Family, Intel® Celeron® Processor N3350, and Intel® Pentium® Processor N4200 Board Support Package for Yocto Project*—MR3.1 Release

3.2.5 Unsupported or discontinued features (p17)
> GStreamer VA PI multi-stream decode with H264 not more supported 
 
Can somebody confirm/clarify this please ?

**Comment by xhaihao** [comment]
Sorry, I don't have such information. We focus on intel-vaapi-driver and libva only, you should check with the owner of MR3.1
