### ISSUE TITLE
AVC encoder quality improvement on SKL/APL

### ISSUE THREAD

**Issue by QuPengfei** [01org/intel-vaapi-driver#43]
This will improve the AVC encoder quality on SKL and APL

**Comment by seanvk** [comment]
Hi, you just need to use the phrase:  "Fixes #n"  Note the spelling and where n is 43.  You have some weird things like "Fix #n" and 01org#n.

**Comment by seanvk** [comment]
@QuPengfei In your recent patch update, where are the actual kernel files?  I don't see them.  All I see is the header with the extern declaration.

**Comment by QuPengfei** [comment]
@Sean the kernel binary file in this patch "ENC: add AVC kernel binary on SKL", include .h/c. it looks too large.

here is the info:
12,085 12,085 additions & 0 deletions  src/gen9_avc_encoder_kernels.c
12,085 additions, 0 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

**Comment by QuPengfei** [comment]
yes, I will correct the spelling. at the same time 01org#n is the issue link, I will remove it.

**Comment by seanvk** [comment]
Ah, I will pull the binaries directly.  I just wanted to make sure the actual kernel files with the binaries were using an Apache 2 header...
