### ISSUE TITLE
H.264 decoder crashes "couldn't find associated picture parameter set with id: 0"

### ISSUE THREAD

**Issue by Faham** [01org/intel-vaapi-driver#52]
[capture.zip](https://github.com/01org/intel-vaapi-driver/files/778410/capture.zip)

Using gstreamer pipeline:

`gst-launch-1.0 filesrc location=./streams/62508/WGN_VU_2016-11-30_09.00.53.ts ! queue max-size-bytes=0 max-size-buffers=0 max-size-time=10000000000 ! tsdemux name=dmx     dmx. ! h264parse ! vaapidecode ! queue max-size-bytes=0 max-size-buffers=0 max-size-time=10000000000 ! vaapisink
`

On a specific content which is provided as an attachment. The provided capture is decoded flawlessly using other software decoders, while it leads to the following errors and crash of the vaapi decoder:

> 0:00:00.782582616 19934       0xf92680 ERROR                  vaapi gstvaapidecoder_h264.c:2648:find_short_term_reference: found no short-term reference picture with PicNum = 882
> 0:00:00.782670450 19934       0xf92680 ERROR                  vaapi gstvaapidecoder_h264.c:2648:find_short_term_reference: found no short-term reference picture with PicNum = 883
> 0:00:00.785492921 19934       0xf92680 ERROR                  vaapi gstvaapidecoder_h264.c:2648:find_short_term_reference: found no short-term reference picture with PicNum = 888
> 0:00:00.785554710 19934       0xf92680 ERROR                  vaapi gstvaapidecoder_h264.c:2648:find_short_term_reference: found no short-term reference picture with PicNum = 889
> 0:00:00.791317991 19934       0xf92680 ERROR                  vaapi gstvaapidecoder_h264.c:2648:find_short_term_reference: found no short-term reference picture with PicNum = 886
> 0:00:00.791373724 19934       0xf92680 ERROR                  vaapi gstvaapidecoder_h264.c:2648:find_short_term_reference: found no short-term reference picture with PicNum = 887
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> Redistribute latency...
> 0:00:03.586209079 19934       0xf92680 WARN       codecparsers_h264 gsth264parser.c:2212:gst_h264_parser_parse_slice_hdr: couldn't find associated picture parameter set with id: 0
> 0:00:03.586248940 19934       0xf92680 ERROR            vaapidecode gstvaapidecode.c:867:gst_vaapidecode_parse_frame: parse error -1
> 0:00:03.586550842 19934       0xf92680 WARN       codecparsers_h264 gsth264parser.c:2212:gst_h264_parser_parse_slice_hdr: couldn't find associated picture parameter set with id: 0
> 0:00:03.586580271 19934       0xf92680 ERROR            vaapidecode gstvaapidecode.c:867:gst_vaapidecode_parse_frame: parse error -1
> 0:00:03.586602723 19934       0xf92680 WARN       codecparsers_h264 gsth264parser.c:2212:gst_h264_parser_parse_slice_hdr: couldn't find associated picture parameter set with id: 0
> 0:00:03.586615079 19934       0xf92680 ERROR            vaapidecode gstvaapidecode.c:867:gst_vaapidecode_parse_frame: parse error -1

**Comment by xhaihao** [comment]
@Faham It seems this is a gstreamer-vaapi bug, please file the bug in gnome bugzilla:

https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer
component: gstreamer-vaapi
