### ISSUE TITLE
Running a transcode from the H.264 of the input file to VP8 results in GPU hang when using the new VP8 encoder

### ISSUE THREAD

**Issue by xhaihao** [01org/intel-vaapi-driver#59]
Platform: BSW+

Command:
./yamitranscode -i <input file> -f 60 --rcmode CBR --ow 1920 --oh 1080 -c VP8 -b 500 -N 1000 -o out.ivf

Standard test input: <http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4>

Note: it occurs with some input files at low bitrates with 60fps only

Please refer to https://lists.freedesktop.org/archives/libva/2017-January/005198.html for details

**Comment by seanvk** [comment]
The media kernel team is investigating.

**Comment by seanvk** [comment]
@xhaihao create a Milestone, title it 1.8.0 and assign this bug to the Milestone.

Thanks,

Sean
