### ISSUE TITLE
imported surface doesn't check the buffer layout

### ISSUE THREAD

**Issue by yakuizhao** [01org/intel-vaapi-driver#62]
When the surface is created in driver internally, it will be allocated based on HW requirement.
But when the surface is imported through buffer_sharing, it doesn't check the layout. In such case maybe the buffer doesn't meet with the HW requirement.

So when the buffer is created through buffer_sharing, it will be better to add the check of layout requirement. For example: pitch.

**Comment by seanvk** [comment]
Thanks for adding this.

**Comment by yakuizhao** [comment]
The issue will be closed after merging the commit(43a75eaadf2c5226654be438e0223a28f577d27a).
