### ISSUE TITLE
README isn't updated for Kaby Lake

### ISSUE THREAD

**Issue by sesse** [01org/intel-vaapi-driver#66]
Hi,

The README doesn't mention that Kaby Lake supports VP9 encode (both 8- and 10-bit), even though the NEWS file mentions it was added in 1.7.1/1.7.3. It should probably be updated.

**Comment by xhaihao** [comment]
The driver doesn't support VP9 10bit encoding on Kaby Lake, we don't mention VP9 10bit encoding in the NEWS

**Comment by sesse** [comment]
Yes, you're right; I misread the NEWS file. The README file looks good now, thanks!
