### ISSUE TITLE
HEVC CQP Encoding has shade on big QP(for example, QP=50)

### ISSUE THREAD

**Issue by seanvk** [01org/intel-vaapi-driver#9]
migrated from Bugzilla [#96545](https://bugs.freedesktop.org/show_bug.cgi?id=96545)
status ASSIGNED severity *normal* in component *intel* for *---*
Reported in version *unspecified* on platform *x86 (IA32)*
Assigned to: PengChen

Original attachment names and IDs:
- _[issue hevc cqp qp50.png](https://bugs.freedesktop.org//attachment.cgi?id=124552)_ (ID 124552)

On 2016-06-16 05:43:12 +0000, Focus.Luo wrote:

> Created attachment 124552
> hevc encoding qp=50
> 
> 1, to do a hevc cqp encoding for 2k yuv input
>  ./mv_encoder -hevc -i ./$filename:${WIDTH}x${HEIGHT} -o ./$testname -SliceHeaderPack 1 -PictureCodingType 0 -RateControl 3  -ISliceQP $qp $gopsetting -FrameRate $fps -ProfileIDC 1 -LevelIDC $level -loglevel 0 -intra_only -NumRefFrames 0 -NumSlices 1 -LCUSize $lcu
> 
> 2, to use Vega to view the encoded bitstream
> 
> 3, found that there are some shade on the decoded picture.

On 2016-07-18 03:40:46 +0000, Focus.Luo wrote:

> for HEVC CBR, hevc_enc_cbr_1080p_ipb_10_gop30_lcu16.h265, using Vega to analyse the encoded output bitstream, found the Max/min/average QP is 44, and then also found the shadow issue

**Comment by FocusLuo** [comment]
1.8.3 release no this issue, so closed it
